In [1]:
from transformers import GPT2Tokenizer, TFGPT2Model, GPT2Config
import tensorflow as tf

In [2]:
physical_devices = tf.config.list_physical_devices('GPU') 
tf.config.experimental.set_memory_growth(physical_devices[0], True)

In [3]:
tokenizer = GPT2Tokenizer.from_pretrained("gpt2", add_prefix_space=True)
# model = TFGPT2Model.from_pretrained("gpt2", return_dict=True)
model = TFGPT2Model.from_pretrained("gpt2")

All model checkpoint layers were used when initializing TFGPT2Model.

All the layers of TFGPT2Model were initialized from the model checkpoint at gpt2.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFGPT2Model for predictions without further training.


In [4]:
tokenizer("Hello world")['input_ids']
tokenizer("  Hello world")['input_ids']

[220, 220, 18435, 995]

In [5]:
inputs = tokenizer("Hi, this is a test and I am a bot", return_tensors="tf")
print(inputs)

{'input_ids': <tf.Tensor: shape=(1, 11), dtype=int32, numpy=
array([[15902,    11,   428,   318,   257,  1332,   290,   314,   716,
          257, 10214]])>, 'attention_mask': <tf.Tensor: shape=(1, 11), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])>}


In [10]:
outputs = model(inputs)
last_hidden_state = outputs.last_hidden_state
print(last_hidden_state)

<class 'transformers.modeling_tf_outputs.TFBaseModelOutputWithPast'>
tf.Tensor(
[[[ 0.049586   -0.2191338  -0.22060315 ... -0.23256269 -0.08462568
   -0.18015   ]
  [ 0.4487133   0.12794214  0.45916533 ... -0.02554812  0.02860656
    0.19434442]
  [ 0.5233359   0.21706821 -0.04357781 ... -0.03384571  0.24853888
    0.45464808]
  ...
  [-0.29279605 -0.71266806 -0.6777717  ...  0.03725895 -0.31483287
    0.36645684]
  [ 0.06012781  0.2515111   0.5805898  ... -0.2687615  -0.509544
    0.44237489]
  [ 0.46943504  0.02301278 -0.70128864 ...  0.19859311  0.14772446
    0.48830646]]], shape=(1, 11, 768), dtype=float32)
